### ISSUE TITLE
pygame.error: Unable to make GL context current

### ISSUE THREAD

**Issue by beeekey** [khimaros/ambit#10]
starting ambit with:
`ambit_gui --verbose
`

results in:

```
[0] Choosing device at USB discovery index 0.
[0] Waiting for initial layout ...
[0] Component attached: Base (1) 00000 (0, 0) - 0 - False :: 
[0] Component attached: Dial (2) 5)> (1, 0) - 270 - False :: 
[0] Component attached: Button (3) 4J9 (2, 0) - 270 - False :: 
[0] Component attached: Button (4) 4KO (3, 0) - 270 - False :: 
[0] Component attached: Button (5) 4Mw (4, 0) - 270 - False :: 
[0] Component attached: Dial (6) 6YI (5, 0) - 270 - False :: 
[0] Component attached: Dial (7) 8y` (6, 0) - 270 - False :: 
[0] Processed layout, ready for input!
[0] Detected Palette firmware version 1.3.1
Exception in thread Thread-6 (worker):
Traceback (most recent call last):
  File "/home/ben/miniconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/ben/miniconda3/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ben/miniconda3/lib/python3.11/site-packages/ambit/render.py", line 360, in worker
    self.tick()
  File "/home/ben/miniconda3/lib/python3.11/site-packages/ambit/render.py", line 306, in tick
    pygame.display.flip()
pygame.error: Unable to make GL context current
[0] Received interrupt, shutting down...
[0] Joining threads and releasing USB interface.
^C[@] Cumulative dropped_leds: 0
[@] Cumulative dropped_screen_strings: 0
[@] Cumulative failed_writes: 0

```

**Comment by khimaros** [comment]
thank you for the report @beeekey -- are you running this on MacOS? if so, this may be related to https://github.com/khimaros/ambit/issues/3

more generally, could you provide some extra information? which version of python, pygame, SDL, OpenGL, operating system, window manager, etc?

another possibility is that this is a wayland related issue, in which case you may try launching with SDL_VIDEODRIVER=x11

potentially related, since we are launching pygame in a new thread: https://stackoverflow.com/questions/34629458/pygame-error-unable-to-create-gl-context

**Comment by beeekey** [comment]
Ubuntu Budgie  23.10 (no wayland)

2 Graphic Cards (Onboard Intel and Nvidia GTX 3060) running on Nvidia

I think somwhere here is the problem.

**Comment by khimaros** [comment]
@beeekey i've bumped all dependencies and modernized the repository using mise and uv. if you are still interested in using this, please take it for another spin.

**Comment by beeekey** [comment]
> @beeekey i've bumped all dependencies and modernized the repository using mise and uv. if you are still interested in using this, please take it for another spin.

Nice, I will test it. Have you tested Wayland?

**Comment by khimaros** [comment]
yes. i am using wayland here. also as an FYI, i'm working on a rewrite in rust for easier distribution which is already beyond feature parity with ambit. i haven't published yet but will notify here once i do.

**Comment by khimaros** [comment]
sextant v0.1.0 is ready: https://github.com/khimaros/sextant/releases/tag/v0.1.0

please take it for a spin
